### ISSUE TITLE
看上去是 API 错误

### ISSUE THREAD

**Issue by ctlee61** [WeCase/WeCase#124] opened 2014-05-17 10:40 UTC
苍天啊，大地啊！这个不明错误怎么就发生了呢，
Please report it to http://bugs.wecase.org/
------------[ cut here ]------------

Version: WeCase 0.06-beta5-2456d12-dirty

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/site-packages/WeCase/WeHack.py", line 30, in run_with_except_hook
    run_old(_args, *_kw)
  File "/usr/lib/python3.4/threading.py", line 868, in run
    self._target(_self._args, *_self._kwargs)
  File "/usr/local/lib/python3.4/site-packages/WeCase/Tweet.py", line 99, in _common_get
    timeline = timeline_func()
  File "/usr/local/lib/python3.4/site-packages/WeCase/Tweet.py", line 157, in timeline_get
    timeline = self.timeline.get(page=page, uid=self._uid).statuses
  File "/usr/local/lib/python3.4/site-packages/WeCase/weibos/client.py", line 52, in __call__
    return super(_UBExecutable, self).__call__(*_kw)
  File "/usr/local/lib/python3.4/dist-packages/weibo3.py", line 291, in **call**
    return _http_call('%s%s.json' % (self._client.api_url, self._path), method, self._client.access_token, *_kw)
  File "/usr/local/lib/python3.4/dist-packages/weibo3.py", line 161, in _http_call
    raise APIError(r.error_code, r.get('error', ''), r.get('request', ''))
weibo3.APIError: APIError: 21335: request uid's value must be the current user, request: /2/statuses/user_timeline.json
---[ end trace 0x7f3ba0159e28 ]---

**Comment by biergaizi** [comment] 2014-05-17 11:53
请仔细看看现有的 Issues，不要重复报告，谢谢！

**Comment by biergaizi** [comment] 2014-05-17 11:54
Duplicate of #119.

**Closed as completed by biergaizi** 2014-05-17 11:53 UTC
Labels: duplicate
